dubbo:
  application:
    name: payment-redis-provider
  registry:
    address: zookeeper://10.22.31.103:2181?backup=10.22.31.116:2181,10.22.31.123:2181
    # 读者请自行更改zookeeper地址
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30003
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000
  metadata-report:
    address: zookeeper://10.22.31.103:2181?backup=10.22.31.116:2181,10.22.31.123:2181
    retry-times: 30
    retry-period: 5000
    cycle-report: false

server:
  port: 8061



#redis配置
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
#    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
#    password:
    #读取超时时间
    read-timeout: 3000
    #是否集群
    is-cluster: true
    #集群
    cluster:
      nodes: 10.22.31.103:7000,10.22.31.116:7000,10.22.31.123:7000,10.22.31.103:7001,10.22.31.116:7001,10.22.31.123:7001
      #最大重定向次数
      max-redirects: 20
    # 连接超时时间（毫秒）
    timeout: 5000
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
      # 连接池中的最大空闲连接
        max-idle: 8
  # 连接池中的最小空闲连接
        min-idle: 0

